import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";

import Footer from "@/components/sections/Footer";
import { Navbar } from "@/components/sections/Navbar";

import LenisProvider from "../../contexts/LenisProvider";
import { UserProvider } from "../../contexts/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  adjustFontFallback: false,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "BLOG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <LenisProvider>
            <Navbar />
            {/* <WindowSize /> */}
            {children}
            <Toaster />
            <Footer />
          </LenisProvider>
        </UserProvider>
      </body>
    </html>
  );
}
